### ISSUE TITLE
doesn't obey how many ports selected at installation time, always starts 4

### ISSUE THREAD

**Issue by ciscon** [nQuake/server-linux#46]
after configuration we see:

Install directory:   /home/ciscon/nquakesv
Hostname:            asdf
Listen address:      <resolve address>
Number of ports:     1
RCON password:       asdf
Install QTV:         no
Install QWFWD:       no
Admin:               ciscon <ciscon@example.com>
Search for pak1:     <do not search>

but when starting the ports using start_servers.sh:

 $ ./start_servers.sh
* Starting mvdsv #1 (port 28501)...[OK]
* Starting mvdsv #2 (port 28502)...[OK]
* Starting mvdsv #3 (port 28503)...[OK]
* Starting mvdsv #4 (port 28504)...[OK]

and we can see that it configured 4 ports for us in ~/.nquakesv/ports:

 $ ls ~/.nquakesv/ports/
28501  28502  28503  28504

**Comment by eb** [comment]
Yea, ok, that's actually, because the ~/.nquakesv directory already exists and has the four ports in there. The directory isn't cleared when installing, so it's generating 4 port configs when first started. Should be an easy fix by simply deleting the ~/.nquakesv directory when doing an installation.
