### ISSUE TITLE
Does not work on Ubuntu Server 24.04 - no sockets found in screen.

### ISSUE THREAD

**Issue by ajsweden** [nQuake/server-linux#50]
Ubuntu Server 24.04

Can´t connect to server. Start command is ok. But stop command give error.

user@server:~$ $(cat ~/.nquakesv/install_dir)/start_servers.sh
* Starting mvdsv #1 (port 28501)...[OK]
user@server:~$ $(cat ~/.nquakesv/install_dir)/stop_servers.sh
* Stopping mvdsv (port 28501)...[NOT RUNNING]
No Sockets found in /run/screen/S-user.

Any solutions? Worked fine on Ubuntu Server 22.04.

**Comment by ciscon** [comment]
i'm assuming mvdsv just didn't start properly, can you try to run it manually and see if it works?
cd "$(cat ~/.nquakesv/install_dir)"
./mvdsv

**Comment by ajsweden** [comment]
Tried but .mvdsv gives this:

Illegal instruction (core dumped)

**Comment by ajsweden** [comment]
Typo above.

./mvdsv gives this:

Illegal instruction (core dumped)

**Comment by ciscon** [comment]
you probably just need to compile mvdsv/ktx yourself, usually this is because it was compiled with optimizations your cpu doesn't support, though in the case of mvdsv/ktx we're not setting ourselves so it is a bit of a mystery as to why that would happen.  if you'd like to you can first attempt to use one of the nightlies instead to see if they fix it: https://builds.quakeworld.nu/mvdsv/snapshots/latest/linux/amd64/mvdsv
https://builds.quakeworld.nu/ktx/snapshots/latest/linux/amd64/qwprogs.so

**Comment by ajsweden** [comment]
Weird. It worked perfectly with Ubuntu Server 22.04 on an Intel NUC with J5005 Cpu . Did a fresh clean install Ubuntu Server 24.04 and now it doesn´t work.

Thanks for the tips!

**Comment by ajsweden** [comment]
ciscon: Thanks a lot! The latest builds of mvds and qwprogs.so solved the problem for me :)!

> you probably just need to compile mvdsv/ktx yourself, usually this is because it was compiled with optimizations your cpu doesn't support, though in the case of mvdsv/ktx we're not setting ourselves so it is a bit of a mystery as to why that would happen. if you'd like to you can first attempt to use one of the nightlies instead to see if they fix it: https://builds.quakeworld.nu/mvdsv/snapshots/latest/linux/amd64/mvdsv https://builds.quakeworld.nu/ktx/snapshots/latest/linux/amd64/qwprogs.so
